# Generated by Django 2.2.6 on 2019-10-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount', models.PositiveIntegerField()),
                ('username', models.TextField()),
                ('status', models.CharField(default='unsold', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bid_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('fullname', models.TextField()),
                ('emailid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('username', models.TextField()),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
