# Generated by Django 2.2.6 on 2019-10-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='status',
            field=models.CharField(default='Inprogress', max_length=25),
        ),
        migrations.AlterField(
            model_name='bid_user',
            name='emailid',
            field=models.CharField(max_length=25, null='False'),
        ),
        migrations.AlterField(
            model_name='bid_user',
            name='fullname',
            field=models.CharField(max_length=25, null='False'),
        ),
        migrations.AlterField(
            model_name='bid_user',
            name='password',
            field=models.CharField(max_length=25, null='False'),
        ),
        migrations.AlterField(
            model_name='bid_user',
            name='username',
            field=models.CharField(max_length=25, null='False'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='title',
            field=models.CharField(max_length=25, null='False'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='username',
            field=models.CharField(max_length=25, null='False'),
        ),
    ]
