# Generated by Django 2.2.6 on 2019-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191002_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='amount',
            field=models.PositiveIntegerField(null='False'),
        ),
    ]
